# Book settings
title: Programming Differential Privacy
author: Joseph P. Near and Chiké Abuah
copyright: "© 2025 Joseph P. Near and Chiké Abuah"
description: >
  A practical introduction to programming differential privacy, with a focus on
  the Python programming language.
language: en
logo: logo.png
license:
  name: "CC BY-NC-SA 4.0"
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/

execute:
  timeout: -1
  execute_notebooks: force

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    language: en
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    myst_enable_extensions:
      - amsmath
      - dollarmath

html:
  favicon                   : favicon.png
  use_edit_page_button      : true
  use_repository_button     : true
  use_issues_button         : true

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/uvm-plaid/programming-dp
  path_to_book: notebooks
  branch: master

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"
